### PR TITLE
fix issue #79 preventing copy of ParameterDescription

### PR DESCRIPTION
**Pull request by fbordignon**
The issue was that those lines are constructing and copying the result to a map.
I've worked around that by erasing if the object exists inside the map and constructing the new one in place with emplace.

### CODE REVIEW

**Comment by marsaev** [comment]
Hey, @fbordignon , thanks for taking your time looking into this issue! Can i ask you to push the fix into v2.1.x branch? It's our current dev branch and we will eventually merge it into main and create new release.

**Comment by fbordignon** [comment]
@marsaev did this before my morning coffee, so please ignore the force pushes to my local branch. Anyway, I've replaced tabs with spaces and created a new PR for the dev branch. Thanks for advising.

I had this issue exactly as described using:

CMAKE 3.17.2
Cmakecache https://pastebin.com/QSznNvCh
CMAKE_NO_MPI checked

Visual studio 2019
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x64
Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.

nvcc: NVIDIA (R) Cuda compiler driver
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243

**Comment by marsaev** [comment]
merged in #136

**Comment by marsaev** [comment]
> The swap seems to be in the incorrect branch of the if () - the copy direction is source -> target as the comment indicates so after this change both the preconditioner and the non-preconditioned versions are incorrect.

@petrkodl Just to make sure - were you referencing issue #28 ? If so it was corrected in https://github.com/NVIDIA/AMGX/commit/12f80caffedece37a230d620eabe039cfbaedf6f

**Comment by petrkodl** [comment]
Thanks - I was working with Matthew on that patch.

**Pull request closed without merging**
