### PR TITLE
fix issue #79 preventing copy of ParameterDescription

### PR DESCRIPTION
**Pull request by fbordignon**
Pushing small fix for issue #79 to dev branch

### CODE REVIEW

**Comment by marsaev** [comment]
Ok, weird, i just build on W10, VS2019, msvc version 19.28, and didn't see errors mentioned in #79 (after change 904f2c3c7ad798a36191a1dd1516845062777117). What msvc version do you use?
I'll try to build on VS2019 with your change too.

**Comment by fbordignon** [comment]
Hi marsaev,
cl.exe gives me this info:
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x64

I confirmed the issue using the latest commit on branch v2.1.x  ef4b89cfd21d9ee53978eabc87b043a5b41316f6

**Comment by marsaev** [comment]
Thanks, i'm checking your change with compiler 19.28, if there wouldn't be any issues either - i'll merge it.

**Comment by marsaev** [comment]
Ok, build are fine. Again, i don't see error from #79 with or without this fix, but if that resolves the issue for 19.23 compiler - i'll gladly take it. 

Thanks!

**Comment by fbordignon** [comment]
Hi @marsaev the example of the c_api failing with this fix for vs2019. Maybe it is better to roll back and examine it further.

**Comment by marsaev** [comment]
What cmake, msvc (19.23?), cuda versions do you have?

**Comment by marsaev** [comment]
@fbordignon ok, i only checked the build status because thought this change was minor enough, but apparently it breaks AMGX. I reverted your change. As for now i'll consider #79 resolved as i cannot reproduce it with MSVS 2019.

**Comment by marsaev** [comment]
another argument towards investing time in proper CI/CD :)

**Comment by fbordignon** [comment]
Hi @marsaev . Yes it breaks AMGX for some reason, I also thought it was small enough to push it. I've tested a mockup code separately from AMGX, even with objects with the same types, but something beyond my limited skills is happening.
Sorry for not replying sooner, I was trying to compile AMGX just to see if its going to be of use for a future project. I am going to perform more tests now and report back. Thanks

**Pull request merged**
